# Список публикаций
GET http://localhost:3000/api/articles HTTP/1.1

###

# Полная информация о публикации
GET http://localhost:3000/api/articles/EZcbCf HTTP/1.1

###

# Список категорий
GET http://localhost:3000/api/category HTTP/1.1

###

# Создание новой публикации
POST http://localhost:3000/api/articles HTTP/1.1
Content-Type: application/json

{
  "id": "Prt0Or",
  "title": "Что такое золотое сечение",
  "createdDate": "06.08.2021, 10:02:47",
  "announce": "Он написал больше 30 хитов. Освоить вёрстку несложно. Возьмите книгу новую книгу и закрепите все упражнения на практике. Альбом стал настоящим открытием года. Мощные гитарные рифы и скоростные соло-партии не дадут заскучать. Золотое сечение — соотношение двух величин гармоническая пропорция.",
  "picture": "item03.jpg",
  "fullText": "Собрать камни бесконечности легко если вы прирожденный герой. Этот смартфон — настоящая находка. Большой и яркий экран мощнейший процессор — всё это в небольшом гаджете.",
  "category": [
    "За жизнь",
    "Музыка",
    "Деревья",
    "Кино",
    "Разное",
    "Без рамки",
    "Программирование"
  ]
}

###

# Редактирование публикации
PUT http://localhost:3000/api/articles/Prt0Or HTTP/1.1
Content-Type: application/json

{
  "title": "Как начать программировать",
  "createdDate": "27.08.2021, 01:57:22",
  "announce": "Процессор заслуживает особого внимания. Он обязательно понравится геймерам со стажем. Рок-музыка всегда ассоциировалась с протестами. Так ли это на самом деле? Простые ежедневные упражнения помогут достичь успеха. Освоить вёрстку несложно. Возьмите книгу новую книгу и закрепите все упражнения на практике.",
  "picture": "item07.jpg",
  "fullText": "Обновимся. Это один из лучших рок-музыкантов. Как начать действовать? Для начала просто соберитесь. Освоить вёрстку несложно. Возьмите книгу новую книгу и закрепите все упражнения на практике. Альбом стал настоящим открытием года. Мощные гитарные рифы и скоростные соло-партии не дадут заскучать. Достичь успеха помогут ежедневные повторения. Простые ежедневные упражнения помогут достичь успеха. Помните, небольшое количество ежедневных упражнений лучше, чем один раз, но много.",
  "category": ["Кино", "Музыка"]
}

###

# Удаление публикации
DELETE http://localhost:3000/api/articles/Prt0Or HTTP/1.1

###

# Список комментариев публикации
GET http://localhost:3000/api/articles/SbuSNT/comments HTTP/1.1

###

# Удаление комментария из публикации
DELETE http://localhost:3000/api/articles/SbuSNT/comments/0BEjsp HTTP/1.1

###

# Создание нового комментария
POST http://localhost:3000/api/articles/SbuSNT/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Это новый комментарий"
}

###

# Получение результата поиска
GET http://localhost:3000/api/search?query=Борьба HTTP/1.1

###

